# Input files
input_alignment: "./inputs/pdc_all_orgs.fasta"
db_location: /datasets/UniprotKB/
target_dbs:
  - "uniprot_sprot.fasta"
  - "uniprot_trembl.fasta"

# hmm search
hmmbuild_options: "--amino"
hmmsearch_evalue: 1e-90
min_coverage: 0.85

# clustering
mmseqs_min_seq_id: 0.9
mmseqs_coverage: 0.9