# Input files
input_alignment: "./inputs/pdc_all_orgs.fasta"
target_db: "/datasets/UniprotKB/uniprot_sprot.fasta"

# HMMbuild parameters
hmmbuild_options: "--amino"

# HMMsearch parameters
hmmsearch_evalue: 1e-20
hmmsearch_domevalue: 1e-20

# Filtering parameters
min_coverage: 0.7
