# Input files
input_alignment: "./inputs/characterized.fasta"
target_db: "/datasets/UniprotKB/uniprot_sprot.fasta"

# HMMbuild parameters
hmmbuild_options: "--amino --fast"

# HMMsearch parameters
hmmsearch_evalue: 1e-20
hmmsearch_domevalue: 1e-20

# Filtering parameters
min_coverage: 0.7

# Output directories
intermediates_dir: "./intermediates"
results_dir: "./results"